env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:flowtype/recommended'
ignorePatterns:
  - 'flow-typed/**'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - flowtype
rules:
  {
    'react/jsx-filename-extension': ['warn', { 'extensions': ['.js', '.jsx'] }],
    'react/jsx-sort-props': ['error'],
    'no-unused-vars':
      [
        'error',
        { 'vars': 'all', 'args': 'after-used', 'ignoreRestSiblings': false },
      ],
  }
