env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:@typescript-eslint/recommended'
ignorePatterns:
  - 'build/**'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - simple-import-sort
  - '@typescript-eslint'
rules:
  {
    'prettier/prettier': 'warn',
    'react/jsx-filename-extension':
      ['warn', { 'extensions': ['.js', '.jsx', 'tsx'] }],
    'react/jsx-sort-props': ['warn'],
    'no-unused-vars':
      [
        'warn',
        { 'vars': 'all', 'args': 'after-used', 'ignoreRestSiblings': false },
      ],
    'simple-import-sort/imports': 'warn',
    'simple-import-sort/exports': 'warn',
  }
settings:
  react:
    version: detect
