env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:flowtype/recommended'
ignorePatterns:
  - 'flow-typed/**'
  - 'build/**'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - flowtype
  - simple-import-sort
rules: {
    'react/jsx-filename-extension':
      ['warn', { 'extensions': ['.js', '.jsx', 'tsx'] }],
    'react/jsx-sort-props': ['error'],
    'no-unused-vars':
      [
        'error',
        { 'vars': 'all', 'args': 'after-used', 'ignoreRestSiblings': false },
      ],
    'flowtype/no-types-missing-file-annotation': 1,
    # 'simple-import-sort/imports': 'error',
    # 'simple-import-sort/exports': 'error',
  }
