env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:flowtype/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - flowtype
rules:
  {
    'react/jsx-filename-extension': [ 'warn', { 'extensions': [ '.js', '.jsx' ] } ] ,
    "react/jsx-sort-props": [ 'error' ]
  }
